### ISSUE TITLE
Improved adding RSS feed

### ISSUE THREAD

**Issue by taevel02** [parksb/collie#12]
Hi, Collie is a good service and I'm using it well.

However, I am adding an RSS feed and would like some improvements. I plan to send out separate PR for each item.

1. automatic RSS registration
If a user doesn't manually register their RSS address, it should automatically find and register them if they provide one. If not, it should pop up an appropriate error message.

2. Don't fetch old posts
I would like to add an option to not import previous posts. For example, if a user registers a lot of RSS at once, it's annoying to have to read them all.

I look forward to your feedback and would love to contribute to Collie if you get the chance.

**Comment by parksb** [comment]
It looks good :) but I have a couple of questions.

1. Please explain how to get an RSS address automatically.
2. Could you let me know how you'll provide that option? Will you add a checkbox UI like the image below?
  ![](https://github.com/parksb/collie/assets/6410412/8dfc854a-050d-4395-9b73-7ce1c3c7f896)

**Comment by taevel02** [comment]
> It looks good :) but I have a couple of questions.
> 
> 1. Please explain how to get an RSS address automatically.
> 2. Could you let me know how you'll provide that option? Will you add a checkbox UI like the image below?

Thanks for the comment, here's mine.

1. The ability to automatically get RSS addresses was inspired by [Telegram bot RSS](https://t.me/rss2tg_bot). While there are limitations to adding support for all websites, I'm thinking of the following methods.
    1) Looking for RSS links within the HTML link tags of websites
    2) Automatically registering the RSS if it's provided by default, such as YouTube.
        a. `https://www.youtube.com/{channel_id}` if you enter
        b. `https://www.youtube.com/feeds/videos.xml?channel_id={channel_id}` will be registered

2. Yes, I thought about adding a UI like the one below, but I didn't take that into account when I wrote the issue. I apologize and thank you for catching my mistake.

**Comment by parksb** [comment]
Great. Collie welcomes all contributions. Send PRs and I'll review it.

**Comment by taevel02** [comment]
Thank you, but I'm busy during the week, so I can send PRs on the weekend. I'll send it on Saturday.
