### ISSUE TITLE
Atom Feeds Support

### ISSUE THREAD

**Issue by Suleman-Elahi** [parksb/collie#9]
I think for now, it doesn't support Atom feeds.

Example: https://blogs.windows.com/windows-insider/feed/

I tried adding it to the software but nothing happened. I am using Windows build.

**Comment by parksb** [comment]
This issue occurs because the host responds HTML document, not RSS or Atom when user-agent header is not given. I fixed it from ab4176033f257e27dd7afb31d4cfab4186c89859.
